all:
	#g++ -DLINUX -I. -I ../../../../../../src -std=gnu++11 Transmitter.cpp -o Transmitter -lwiringPi -lpthread -lcrypt -lm -lrt
	g++ -DLINUX -I. -I ../../../../../../libraries/PJON-11.0/src -std=gnu++11 Transmitter.cpp -o Transmitter -lwiringPi -lpthread -lcrypt -lm -lrt
