steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'docker/Dockerfile', '-t', 'ubuntu-runner', '.']

- name: 'ubuntu-runner'
  args: ['bash', 'docker/run_tests.sh']
  id: py2_without_cython
  env:
    - DISABLE_CYTHON=1

- name: 'ubuntu-runner'
  args: ['bash', 'docker/run_tests.sh']
  id: py2_with_cython
  env:
    - FORCE_CYTHON=1

- name: 'ubuntu-runner'
  args: ['bash', 'docker/run_tests.sh']
  id: py3_without_cython
  env:
    - DISABLE_CYTHON=1
    - PYTHON3=1

- name: 'ubuntu-runner'
  args: ['bash', 'docker/run_tests.sh']
  id: py3_with_cython
  env:
    - FORCE_CYTHON=1
    - PYTHON3=1
